[[library.book]]
author = "J.R.R. Tolkien"
available = true
title = "The Hobbit"
year = 1937

[[library.book]]
author = "Frank Herbert"
available = false
title = "Dune"
year = 1965

[[library.book]]
author = "William Gibson"
available = true
title = "Neuromancer"
year = 1984

